@startuml UseCase
actor Admin
actor User

package "Elpun Community" {
  usecase "Manage Jadwal Acara" as UC1
  usecase "Tambah Jadwal" as UC2
  usecase "Edit Jadwal" as UC3
  usecase "Hapus Jadwal" as UC4
  usecase "Lihat Jadwal Acara" as UC5
}

Admin --> UC1 : Kelola Jadwal
Admin --> UC2 : Menambah Jadwal
Admin --> UC3 : Mengedit Jadwal
Admin --> UC4 : Menghapus Jadwal

User --> UC5 : Melihat Jadwal

UC1 --> UC2 : Termasuk
UC1 --> UC3 : Termasuk
UC1 --> UC4 : Termasuk
UC5 --> UC2 : Melihat Jadwal Tersedia

@enduml
